version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - TRINO_HOST=your-trino-host
      - TRINO_PORT=8080
      - TRINO_USER=admin
      - TRINO_CATALOG=icebergrest

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true